// Build step: assemble the single-source system prompt (frame + KB 00..08), embed the page
// HTML, and bake PROMPT_VERSION from a hash of the whole prompt surface. Writes
// src/generated/bundle.js, which the Worker imports.
//
// Runs automatically before `wrangler dev` / `wrangler deploy` (see [build] in wrangler.toml),
// and via `npm run build`. The generated file is gitignored: the deployed artifact is always
// regenerated from the current prompt/ + kb/ + ui/, so a KB edit can never ship stale.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

const manifest = JSON.parse(read("prompt/manifest.json"));
const frame = read("prompt/00-system-frame.md").trimEnd();

// Concatenate the KB in manifest order. Each KB file (except the index) is tagged with its
// canonical module slug so the model can map content -> envelope module reliably.
const kbParts = manifest.files.map(({ file, module }) => {
  const body = read(join("kb", file)).trim();
  const tag = module ? "<!-- module-slug: " + module + " -->\n" : "";
  return tag + body;
});

const systemPrompt = frame + "\n\n" + kbParts.join("\n\n\n") + "\n";

// PROMPT_VERSION = <kb manifest>+<prompt rev>+<short content hash>. The hash covers the whole
// prompt, so any KB or frame edit changes the version even if someone forgets to bump the rev.
const hash = createHash("sha256").update(systemPrompt).digest("hex").slice(0, 8);
const PROMPT_VERSION = manifest.kbManifest + "+" + manifest.promptRev + "+" + hash;

const pageHtml = read("ui/index.html");

const out =
  "// AUTO-GENERATED by scripts/build-prompt.mjs. Do not edit. Do not commit (gitignored).\n" +
  "// Regenerated on every build/dev/deploy from prompt/ + kb/ + ui/.\n\n" +
  "export const PROMPT_VERSION = " + JSON.stringify(PROMPT_VERSION) + ";\n\n" +
  "export const SYSTEM_PROMPT = " + JSON.stringify(systemPrompt) + ";\n\n" +
  "export const PAGE_HTML = " + JSON.stringify(pageHtml) + ";\n";

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/bundle.js"), out);

// Rough token estimate (~3.5 chars/token for English prose) for the cost model sanity check.
const approxTokens = Math.round(systemPrompt.length / 3.5);
console.log("[build] PROMPT_VERSION = " + PROMPT_VERSION);
console.log("[build] system prompt: " + systemPrompt.length + " chars (~" + approxTokens + " tokens)");
console.log("[build] page html: " + pageHtml.length + " chars");
console.log("[build] wrote src/generated/bundle.js");
